version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./.docker/app
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    ports: 
        - 6001:6001
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mariadb:10.5.8
    container_name: app-mariadb
    restart: unless-stopped
    ports:
      - 3304:3304
    volumes:
      - app-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - 88:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  app-volume:
    driver: local